services:
  repository-proxy:
    build: .
    image: repository-proxy:latest
    ports:
      - 127.0.0.1:8082:8082
    environment:
      - PORT=8082
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MAX_DOWNLOAD_BYTES=${MAX_DOWNLOAD_BYTES:-}
      - CLOUDFLARE_TUNNEL=true
    env_file:
      - .env
